# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

class FindParameter():
  def __init__(self):
    self.setup_method()
    try:
      self.test_t1()
    except Exception as exp:
      print(exp)
      self.teardown_method()

  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_t1(self):
    self.driver.get("https://www.tradingview.com/")
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".active .tv-signin-dialog__social").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("codachang0726")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("/59L/vN/BgAd%j!")
    self.driver.find_element(By.CSS_SELECTOR, ".tv-button--thin-border > .tv-button__loader").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tv-feed-block:nth-child(1) > .tv-feed-block__header").click()
    self.driver.get("https://www.tradingview.com/")
  

FindParameter()